using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;

namespace Devlooped;

[Generator(LanguageNames.CSharp)]
public class NameOfGenerator : IIncrementalGenerator
{
    static readonly DiagnosticDescriptor TypeNotFound = new(
        id: "NAMEOF001",
        title: "NameOf type not found",
        messageFormat: "Could not find type '{0}' in the compilation",
        category: "NameOf",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var options = context.AnalyzerConfigOptionsProvider.Select(static (options, _) =>
        {
            options.GlobalOptions.TryGetValue("build_property.NameOf_Types", out var types);
            options.GlobalOptions.TryGetValue("build_property.RootNamespace", out var rootNamespace);
            return (Types: types ?? "", RootNamespace: rootNamespace ?? "NameOf");
        });

        var combined = options.Combine(context.CompilationProvider);

        context.RegisterSourceOutput(combined, static (ctx, pair) =>
        {
            var ((types, rootNamespace), compilation) = pair;
            if (string.IsNullOrWhiteSpace(types))
                return;

            foreach (var fqtn in types.Split('|'))
            {
                var typeName = fqtn.Trim();
                if (string.IsNullOrEmpty(typeName))
                    continue;

                var typeSymbol = compilation.GetTypeByMetadataName(typeName);
                if (typeSymbol is null)
                {
                    ctx.ReportDiagnostic(Diagnostic.Create(TypeNotFound, Location.None, typeName));
                    continue;
                }

                var simpleName = typeSymbol.Name;
                var isGeneric = typeSymbol.TypeParameters.Length > 0;
                var properties = GetPublicProperties(typeSymbol);

                var source = GenerateSource(rootNamespace, simpleName, typeName, isGeneric, properties);
                ctx.AddSource($"NameOf.{simpleName}.g.cs", source);
            }
        });
    }

    static ImmutableArray<string> GetPublicProperties(INamedTypeSymbol typeSymbol)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        var result = ImmutableArray.CreateBuilder<string>();

        var current = (ITypeSymbol)typeSymbol;
        while (current is not null && current.SpecialType != SpecialType.System_Object)
        {
            foreach (var member in current.GetMembers().OfType<IPropertySymbol>())
            {
                if (member.DeclaredAccessibility == Accessibility.Public &&
                    !member.IsIndexer &&
                    seen.Add(member.Name))
                {
                    result.Add(member.Name);
                }
            }
            current = current.BaseType!;
        }

        result.Sort(StringComparer.Ordinal);
        return result.ToImmutable();
    }

    static string GenerateSource(string rootNamespace, string simpleName, string fqtn, bool isGeneric, ImmutableArray<string> properties)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.Append("namespace ").Append(rootNamespace).AppendLine(";");
        sb.AppendLine();
        sb.AppendLine("partial class NameOf");
        sb.AppendLine("{");
        sb.Append("    public static readonly HashSet<string> ").Append(simpleName).AppendLine(" =");
        sb.AppendLine("    [");

        foreach (var prop in properties)
        {
            if (isGeneric)
                sb.Append("        \"").Append(prop).AppendLine("\",");
            else
                sb.Append("        nameof(").Append(fqtn).Append('.').Append(prop).AppendLine("),");
        }

        sb.AppendLine("    ];");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
